config/routes.rb
Avalon::Application.routes.draw do
  mount BrowseEverything::Engine => '/browse'

      get '/bookmarks/delete', as: :delete_bookmarks
      post '/bookmarks/delete'
      get '/bookmarks/move', as: :move_bookmarks
      post '/bookmarks/move'
      get '/bookmarks/update_access_control', as: :update_access_control_bookmarks
      post '/bookmarks/update_access_control'
      post '/bookmarks/publish', as: :publish_bookmarks
      post '/bookmarks/unpublish', as: :unpublish_bookmarks
      post '/bookmarks/archive', as: :archive_bookmarks

  post '/media_objects/set_session_quality'

  blacklight_for :catalog

  root :to => "catalog#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, format: false
  devise_scope :user do 
    match '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session, via: [:get]
    match '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session, via: [:get]
  end
  match "/authorize", to: 'derivatives#authorize', via: [:get, :post]
  match "/authorize/:path", to: 'derivatives#authorize', via: [:get, :post]
  match "/autocomplete", to: 'object#autocomplete', via: [:get]
  match "/oembed", to: 'master_files#oembed', via: [:get]

  match "object/:id", to: 'object#show', via: [:get], :as => :object
  resources :media_objects, except: [:create] do    
    member do
      put :update_status
      get :progress, :action => :show_progress
      get 'content/:datastream', :action => :deliver_content, :as => :inspect
      get 'track/:part', :action => :show, :as => :indexed_section
      get 'section/:content', :action => :show, :as => :pid_section
      get 'tree', :action => :tree, :as => :tree
      get :confirm_remove
      get 'archive',:action => :archive
      get 'manifest',:action => :manifest
    end
    collection do
      get :confirm_remove
      put :update_status
      delete :remove, :action => :destroy
      get :confirm_reassign_collection
      put :reassign_collection
    end
  end
  resources :master_files, except: [:new, :index, :update] do
    member do
      get  'thumbnail', :to => 'master_files#get_frame', :defaults => { :type => 'thumbnail' }
      get  'poster',    :to => 'master_files#get_frame', :defaults => { :type => 'poster' }

      post 'thumbnail', :to => 'master_files#set_frame', :defaults => { :type => 'thumbnail', :format => 'html' }
      post 'poster',    :to => 'master_files#set_frame', :defaults => { :type => 'poster', :format => 'html' }
      post 'still',     :to => 'master_files#set_frame', :defaults => { :format => 'html' }
      get :embed
      post 'attach_structure'
    end
  end

  match '/media_objects/:media_object_id/section/:id/embed' => 'master_files#embed', via: [:get]
  resources :derivatives, only: [:create]
  
  resources :comments, only: [:index, :create]

  namespace :admin do
    resources :groups, except: [:show] do 
      collection do 
        put 'update_multiple'
      end
      member do
        put 'update_users'
      end
    end
    resources :collections do
      member do
        get 'edit'
        get 'remove'
      end
    end
  end

  resources :dropbox, :only => [] do
    collection do
      delete :bulk_delete
    end
  end

  mount AboutPage::Engine => '/about(.:format)', :as => 'about_page'
  

end

app/helpers/media_objects_helper.rb
# Copyright 2011-2015, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

module MediaObjectsHelper
      # Quick and dirty solution to the problem of displaying the right template.
      # Quick and dirty also gets it done faster.
      def current_step_for(status=nil)
        if status.nil?
          status = HYDRANT_STEPS.first
        end
        
        HYDRANT_STEPS.template(status)
      end
     
      # Based on the current context it will choose which class should be
      # applied to the display. If you are not using Twitter Bootstrap or
      # want different defaults then change them here.
      #
      # The context here is the media_object you are working with.
      def class_for_step(context, step)  
        css_class = case 
          # when context.workflow.current?(step)
          #   'nav-info'
          when context.workflow.completed?(step)
            'nav-success'
          else 'nav-disabled' 
          end

        css_class
     end

     def form_id_for_step(step)
       "#{step.gsub('-','_')}_form"
     end

     def dropbox_url collection
        ic = Iconv.new('UTF-8//IGNORE', 'UTF-8')
        path = URI::Parser.new.escape(collection.dropbox_directory_name, %r{[/\\%& #]})
        url = File.join(Avalon::Configuration.lookup('dropbox.upload_uri'), path)
        ic.iconv(url)
     end
     
     def combined_display_date mediaobject
       (issued,created) = case mediaobject
       when MediaObject
         [mediaobject.date_issued, mediaobject.date_created]
       when Hash
         [mediaobject[:document]['date_ssi'], mediaobject[:document]['date_created_ssi']]
       end
       result = issued
       result += " (Creation date: #{created})" if created.present?
       result
     end

     def display_other_identifiers mediaobject
       # bibliographic_id has form [:type,"value"], other_identifier has form [[:type,"value],[:type,"value"],...]
       ids = mediaobject.bibliographic_id.present? ? [mediaobject.bibliographic_id] : []
       ids += Array(mediaobject.other_identifier)
       ids.uniq.collect{|i| "#{ ModsDocument::IDENTIFIER_TYPES[i[0]] }: #{ i[1] }" }
     end

     def display_notes mediaobject
       note_string = ""
       note_types = ModsDocument::NOTE_TYPES.clone
       note_types['table of contents']='Contents'
       sorted_note_types = note_types.keys.sort
       sorted_note_types.prepend(sorted_note_types.delete 'general')
       sorted_note_types.each do |note_type|
         notes = note_type == 'table of contents'? mediaobject.table_of_contents : gather_notes_of_type(mediaobject, note_type)
         notes.each_with_index do |note, i|
           note_string += "<p class='item_note_header'>#{note_types[note_type]}</p>" if i==0 and note_type!='general'
           note_string += simple_format(note, class:'item_note')
         end
       end
       note_string
     end

     def gather_notes_of_type mediaobject, type
       mediaobject.note.present? ? mediaobject.note.select{|n| n[0]==type}.collect{|n|n[1]} : []
     end

     def display_language mediaobject
       mediaobject.language.collect{|l|l[:text]}.uniq
     end

     def display_related_item mediaobject
       mediaobject.related_item_url.collect{ |r| link_to( r[:label], r[:url]) }
     end

     def current_quality stream_info
       available_qualities = Array(stream_info[:stream_flash]).collect {|s| s[:quality]}
       available_qualities += Array(stream_info[:stream_hls]).collect {|s| s[:quality]}
       available_qualities.uniq!
       quality ||= session[:quality] if session['quality'].present? && available_qualities.include?(session[:quality])
       quality ||= Avalon::Configuration.lookup('streaming.default_quality') if available_qualities.include?(Avalon::Configuration.lookup('streaming.default_quality'))
       quality ||= available_qualities.first
       quality
     end

     def parse_hour_min_sec s
       return nil if s.nil?
       smh = s.split(':').reverse
       (Float(smh[0]) rescue 0) + 60*(Float(smh[1]) rescue 0) + 3600*(Float(smh[2]) rescue 0)
     end

     def parse_media_fragment fragment
       return 0,nil if !fragment.present?
       f_start,f_end = fragment.split(',')
       return parse_hour_min_sec(f_start) , parse_hour_min_sec(f_end)
     end

     def is_current_section? section
        @currentStream && ( section.pid == @currentStream.pid )
     end

     def hide_sections? sections
       sections.blank? or (sections.length == 1 && sections.first.structuralMetadata.empty?)
     end

     def structure_html section, index, show_progress
       current = is_current_section? section
       progress_div = show_progress ? '<div class="status-detail alert" style="display: none"></div>' : ''

       headeropen = <<EOF
    <div class="panel-heading" role="tab" id="heading#{index}">
      <h4 class="panel-title #{ 'progress-indented' if progress_div.present? }">
EOF
       headerclose = <<EOF
      #{progress_div} 
      </h4>
    </div>
EOF

       data = {
         segment: section.pid, 
         is_video: section.is_video?, 
         share_link: share_link_for(section), 
         native_url: pid_section_media_object_path(@mediaobject, section.pid)
       } 
       data[:lti_share_link] = user_omniauth_callback_url(action: 'lti', target_id: section) if Avalon::Authentication::Providers.any? {|p| p[:provider] == :lti } 
       duration = section.duration.blank? ? '' : " (#{milliseconds_to_formatted_time(section.duration.to_i)})"

       # If there is no structural metadata associated with this masterfile return the stream info
       if section.structuralMetadata.empty?
         label = "<ul><li><span>#{index+1}. #{stream_label_for(section)} #{duration}</span></li></ul>".html_safe
         link = link_to label, share_link_for( section ), data: data, class: current ? 'current-stream current-section playable' : 'playable'
         return "#{headeropen}#{link}#{headerclose}"
       end

       sectionnode = section.structuralMetadata.xpath('//Item')

       # If there are subsections within structure, build a collapsible panel with the contents
       if sectionnode.children.present?
         tracknumber = 0
         label = "<ul><li><span>#{index+1}. #{sectionnode.attribute('label').value} #{duration}</span></li></ul>".html_safe
         link = link_to label, share_link_for( section ), data: data, class: current ? 'current-stream current-section' : nil
         wrapperopen = <<EOF
          #{headeropen}
          <button class="fa fa-minus-square #{current ? '' : 'hidden'}" data-toggle="collapse" data-target="#section#{index}" aria-expanded="#{current ? 'true' : 'false' }" aria-controls="collapse#{index}"></button>
          <button class="fa fa-plus-square #{current ? 'hidden' : ''}" data-toggle="collapse" data-target="#section#{index}" aria-expanded="#{current ? 'true' : 'false' }" aria-controls="collapse#{index}"></button>
          #{link}
          #{headerclose}

    <div id="section#{index}" class="panel-collapse collapse #{current ? 'in' : ''}" role="tabpanel" aria-labelledby="heading#{index}">
      <div class="panel-body">
        <ul>
EOF
         wrapperclose = <<EOF 
        </ul>
      </div>
    </div>
EOF
       # If there are no subsections within the structure, return just the header with the single section
       else
         tracknumber = index
         wrapperopen = "#{headeropen}<a href='#{share_link_for( section )}'><span><ul>"
         wrapperclose = "</ul></span></a>#{headerclose}"
       end
       contents, tracknumber = parse_section section, sectionnode.first, tracknumber
       "#{wrapperopen}#{contents}#{wrapperclose}"
     end

     def parse_section section, node, index
       sectionnode = section.structuralMetadata.xpath('//Item')
       if sectionnode.children.present?
         tracknumber = 0
         contents = ''
         sectionnode.children.each do |node| 
           next if node.blank?
           st, tracknumber = parse_node section, node, tracknumber
           contents+=st
         end
       else
         contents, tracknumber = parse_node section, sectionnode.first, index        
       end
       return contents, tracknumber
     end
 
     def parse_node section, node, tracknumber
       if node.name.upcase=="DIV"
         contents = ''
         node.children.each do |n| 
           next if n.blank?
           nodecontent, tracknumber = parse_node section, n, tracknumber
           contents+=nodecontent
         end
         return "<li>#{node.attribute('label')}</li><li><ul>#{contents}</ul></li>", tracknumber
       elsif ['SPAN','ITEM'].include? node.name.upcase
         tracknumber += 1
         label = "#{tracknumber}. #{node.attribute('label').value} (#{get_duration node, section})"
         start,stop = get_xml_media_fragment node, section
         native_url = "#{pid_section_media_object_path(@mediaobject, section.pid)}?t=#{start},#{stop}"
         url = "#{share_link_for( section )}?t=#{start},#{stop}"
         data =  {segment: section.pid, is_video: section.is_video?, native_url: native_url, fragmentbegin: start, fragmentend: stop}
         link = link_to label, url, data: data, class: is_current_section?(section) ? 'current-stream playable' : 'playable'
         return "<li class='stream-li'>#{link}</li>", tracknumber
       end
     end

     def get_xml_media_fragment node, section

app/views/media_objects/_administrative_links.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% if can? :update, @mediaobject %>
  <div class="row-fluid">
      <p>
        <ul class="unstyled hidden">
          <li>
            <% if @mediaobject.published? %>
              <span class="label label-success">Published</span> Authorized users can view the item</li>
            <% else %>
              <span class="label label-important">Unpublished</span> Users cannot view the item</li>
            <% end %>
          <li>
            <% unless @mediaobject.discover_groups.include? "nobody" %>
              <span class="label label-success">Visible</span> Users can search for the item</li>
            <% else %>
              <span class="label label-important">Hidden</span> Users cannot search for the item</li>
            <% end %>
        </ul>
      </p>

      <div id="administrative_options" style="margin-bottom:1em;">

      <% if @mediaobject.published? %>
        <% if can?(:unpublish, @mediaobject) %>
          <%= link_to 'Unpublish', update_status_media_object_path(@mediaobject, status:'unpublish'), method: :put, class: 'btn btn-default' %>
        <% end %>
      <% else %>
        <%= link_to 'Publish', update_status_media_object_path(@mediaobject, status:'publish'), method: :put, class: 'btn btn-default' %>
      <% end %>


        <%= link_to 'Edit', edit_media_object_path(@mediaobject), class: 'btn btn-default' %>
        <%# This might not be the best approach because it makes accidental 
            deletion possible just by following a link. Need to revisit when
            extra cycles are available %>

        <% if can? :destroy, @mediaobject %>
          <%= link_to 'Delete', confirm_remove_media_object_path(@mediaobject), class: 'btn btn-danger' %>
        <% end %>
      </div>
  </div>
<% end %>

app/views/media_objects/_dropbox_details.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<div class="well well-info muted">
  Dropbox location: <em><%= dropbox_url(@mediaobject.collection) %></em>
  <br/>
  Contact your system administrator for more information.
  <br/>
</div>

app/views/media_objects/_dropdown_field.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% selected_value ||= options[:dropdown_options].keys.first %>
<% fieldarray = options[:multivalued]? "[]" : "" %>

<div class="input-group-btn">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <span><%= options[:dropdown_options][selected_value] %></span> <span class="caret"></span>
  </button>
  <%= hidden_field_tag "media_object[#{options[:dropdown_field]}]#{fieldarray}", selected_value %>
  <ul class="dropdown-menu" role="menu">
    <% options[:dropdown_options].each_pair do |value, display| %>
    <li><a><%= display %></a><span class="hidden"><%= value %></li>
    <% end %>
  </ul>
</div>

app/views/media_objects/_embed_resource.html.erb
<% if section=='tab-content' %>

    <div class="tab-pane" id="embed-tab">
      <% if @currentStream.present? %>
      <p class="muted">Copy the text below to embed this resource</p>
      <textarea class="col-md-6" rows="3" id="embed-part" onClick="this.select();" readonly="readonly">
        <%= @currentStream.embed_code(MasterFile::EMBED_SIZE[:medium], { urlappend: '/embed' }) %>
      </textarea>
      <% else %>
      <p class="muted"> <%= I18n.t('media_object.empty_share_link_notice') %> </p>
      <% end %>
    </div>

<% elsif section=='share-tabs' %>

    <li><a href="#embed-tab" data-toggle="tab">Embed</a></li>

<% end %>

app/views/media_objects/_structure.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% content_for :additional_head_content do %>
<%= stylesheet_link_tag 'jquery.xmleditor.css' %>
<% end %>

<p class="muted">Drag files to reorder them.</p>

<% if @masterFiles.blank? %>
  <div class="well">There are no media files</div>
<% else %>
  <div id="mediaobject_structure">
    <ul class="header">
      <li>Type</li><li>Section label</li><li>File name</li><li>Size</li><li>Structure</li>
    </ul>
    <ul class="sortable">
      <% @masterFiles.each_with_index do |section, index| %>
      <li class="section" data-segment="<%= section.pid %>">
        <ul class="fileinfo">
          <li>
            <% case section.file_format
               when 'Sound' %>
            <i class="fa fa-volume-up"></i>
            <% when 'Moving image' %>
            <i class="fa fa-film"></i>
            <% else %>
            <i class="fa fa-question-sign"></i>
            <% end %>
	  </li><li>
            <%= section.label.blank? ? '&#8212;'.html_safe : section.label %>
	  </li><li>
            <%= truncate_center(File.basename(section.file_location), 50, 20) %>
	  </li><li>
            <%= number_to_human_size(section.file_size) %>
	  </li><li>
	    <a href="#structure" class="structure_toggle" data-target="structure_<%= index %>" >
	      <i class="fa fa-plus-square"></i>
	      <i class="fa fa-minus-square hidden"></i>
	    </a>
	  </li>
	</ul>
        <div id="structure_<%= index %>" class="hidden structure_xml" >
	  <div class="structure_actions">
	    <%= form_for section, :url => attach_structure_master_file_path(section.pid), html: {method: "post"} do |form| %>
	      <%= form.file_field :structure, class: "filedata", style: "height:0px;width:0px;" %>
	      <input type="button" class="btn btn-primary btn-xs" onclick="$('#structure_<%= index %> .filedata').click();" value="Upload" />
	      <input type="button" class='btn btn-primary btn-xs' value="Edit" data-toggle="modal" data-target="#edit_structure_<%= index %>" />
              <input type="submit" class="btn btn-danger btn-xs" value="Remove" />
	    <% end %>
          </div>
	  <div class="structure_view"/>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

<div/>
<br class="clear"/>
<%= bootstrap_form_for @mediaobject, html: { class: "form-horizontal" } do |media| %>
  <%= render "workflow_buttons" %>
<% end %>

<% @masterFiles.each_with_index do |section, index| %>
  <% default_structure="<Item label='#{stream_label_for(section)}'></Item>" %>
  <div id="edit_structure_<%= index %>" class="structure_edit modal fade" data-backdrop="false" data-submit_url="<%= attach_structure_master_file_path(section.pid) %>">
    <div class="modal-dialog modal-lg">
      <div class="modal-content col-md-12">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Edit Structure</h4>
        </div>
        <div class="modal-body structure_edit col-md-12">
	  <textarea rows=20 class="col-md-12 original_textarea" id="structure_<%= index %>" style="visibility:hidden"><%= section.structuralMetadata.valid? ? section.structuralMetadata.to_xml : default_structure %></textarea>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% end %>

<% content_for :page_scripts do %>
  <%= javascript_include_tag 'sort_streams' %>
  <%= javascript_include_tag 'xmleditor/jquery.xmleditor' %>
  <%= javascript_include_tag 'xmleditor/xsd2json' %>
  <%= javascript_include_tag 'xmleditor/vkbeautify' %>
  <%= javascript_include_tag 'xmleditor/ace' %>
  <%= javascript_include_tag 'xmleditor/mode-xml' %>
<script>

function htmlDecode(value){
  return $('<div/>').html(value).text();
}

function parse_structure(xml,index){
  var $xml = $( $.parseXML(xml) );
  var $item = $xml.find( "Item" );
  if ($item.length) {
    if ($item.children().length) return "<span>"+$item.attr('label')+"</span><ul>"+parse_section($item.first(), index)[0]+"</ul>";
    else return "<span>"+(index+1)+". "+$item.attr('label')+"</span>";
  } else return "";
}

function parse_section (node, index) {
  var contents = '';
  var tracknumber;
  var nodecontents;
  if (node.children().length) {
    tracknumber = 0;
    $.each(node.children(), function( index, node ) {
        nodecontents = parse_node(node, tracknumber);
        contents+=nodecontents[0];
        tracknumber = nodecontents[1];
    });
  } else {
    nodecontents = parse_node(node.first, index);
    contents = nodecontents[0];
    tracknumber = nodecontents[1];
  }
  return [contents, tracknumber];
}

function parse_node(node, tracknumber){
  if (node.nodeName.toUpperCase()=="DIV"){
    var contents = ''
    $.each($(node).children(), function( index, node ) {
      var nodecontents = parse_node(node, tracknumber);
      contents += nodecontents[0];
      tracknumber = nodecontents[1];
    });
    return ["<li>"+$(node).attr('label')+"</li><li><ul>"+contents+"</ul></li>", tracknumber];
  } else if ($.inArray(node.nodeName.toUpperCase(),['SPAN','ITEM']) != -1){
    tracknumber += 1;
    return ["<li class='stream-li'>"+tracknumber+". "+$(node).attr('label')+"</li>", tracknumber];
  } else {
    return ["",tracknumber];
  }
}

$('.structure_toggle').on('click', function (e) { 
  $(this).find('i.fa').toggleClass('hidden');
  target = $(this).data('target')
  section_index = parseInt(target.split('_')[1]);
  populate_structure_preview(section_index)
  $('#'+target).toggleClass('hidden');
});

$( '.filedata' ).change(function() {
  $(this).closest('form').submit();
});

function populate_structure_preview(index){
  $xmltextarea = $('#edit_structure_'+index).find('textarea.original_textarea');
  $('#structure_'+index).find('.structure_view').html(parse_structure(htmlDecode($xmltextarea.html()),index));
}

function attach_structure_response(r) {
  if (r['flash'] && r['flash'].length) {
    msg = ''
    for (var i=0; i<r['flash'].length; i++) {
      for (var j=0; j<r['flash'][i][1].length; j++) {
        msg += r['flash'][i][1][j]+'<br/>';
      }
    }
    return msg;
  } else {
    current_xml_editor.find('textarea.original_textarea').html(r['structure']);
    section_index = parseInt(current_xml_editor.attr('id').split('_')[2]);
    populate_structure_preview(section_index);
    current_xml_editor.modal('hide');
    current_xml_editor = null;
  }
}

var current_xml_editor;
var extractor = new Xsd2Json('avalon_structure.xsd', {'schemaURI':'/', 'rootElement':'item'});
$('.structure_edit.modal').on('shown.bs.modal', function(){
  modal = $(this);
  current_xml_editor = modal;
  te = modal.find('.original_textarea').first();
  footer = modal.find('.modal-footer').first();
  mb = modal.find('.modal-body').first();
  te.height( $(window).height() + modal.offset().top - te.offset().top - footer.height() - (mb.outerHeight()-mb.height()) );
  if (modal.find('.xml_editor_container').length==0) {
    te.xmlEditor({
      schema: extractor.getSchema(),
      floatingMenu: false,
      confirmExitWhenUnsubmitted: false,
      loadSchemaAsychronously: false,
      xmlEditorLabel: 'Graphical',
      textEditorLabel: 'Raw XML',
      containerElement: {
        element: mb,
        fixedHeight: true,
      },
      submitButtonConfigs : [
        {
          url: $(this).data('submit_url'),
          responseHandler: attach_structure_response,
          label: 'Save and Exit',
          cssClass: 'btn btn-primary section_edit_submit',
        }],
      defaultView: 'text',
    });
  }
});
</script>
<% end %>

app/views/media_objects/confirm_remove.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<div class="container-fluid">
    <div class="row-fluid">
      <div class="btn-options">
	<% if params[:id].empty? %>
          <div class="alert alert-danger">
	    <p>No resources were selected.</p>
	  </div>
	  <%= link_to 'Go back', :back, class: 'btn btn-default' %> 
	<% else %>
	  <% params[:id] = Array(params[:id]) %>
          <div class="alert alert-danger">
            <p>Are you certain you want to delete the following <%= 'resource'.pluralize(params[:id].count) %>?</p>
	    <ul>
	      <% params[:id].each do |id| %>
		<% @mediaobject = MediaObject.find(id)  %>
		<% if can? :destroy, @mediaobject  %>
	          <li><%= @mediaobject.title %> (<%= id %>)</li>
	        <% else %>
	          <li><%= @mediaobject.title %> (<%= id %>): permission denied</li>
	        <% end %>
	      <% end %>
	    </ul>
        </div>
	<%= link_to 'Yes, I am sure', remove_media_objects_path( id: params[:id], previous_view: @previous_view ), method: :delete, id: 'deleteLink', name: 'delete', class: 'btn btn-danger' %>
	<%= link_to 'No, go back', :back, class: 'btn btn-default' %> 
	<% end %>
      </div>
    </div>
</div>