config/routes.rb
Avalon::Application.routes.draw do
  mount BrowseEverything::Engine => '/browse'

      get '/bookmarks/delete', as: :delete_bookmarks
      post '/bookmarks/delete'
      get '/bookmarks/move', as: :move_bookmarks
      post '/bookmarks/move'
      get '/bookmarks/update_access_control', as: :update_access_control_bookmarks
      post '/bookmarks/update_access_control'
      post '/bookmarks/publish', as: :publish_bookmarks
      post '/bookmarks/unpublish', as: :unpublish_bookmarks
      post '/bookmarks/archive', as: :archive_bookmarks

  post '/media_objects/set_session_quality'

  blacklight_for :catalog

  root :to => "catalog#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, format: false
  devise_scope :user do 
    match '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session, via: [:get]
    match '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session, via: [:get]
  end
  match "/authorize", to: 'derivatives#authorize', via: [:get, :post]
  match "/authorize/:path", to: 'derivatives#authorize', via: [:get, :post]
  match "/autocomplete", to: 'object#autocomplete', via: [:get]
  match "/oembed", to: 'master_files#oembed', via: [:get]

  match "object/:id", to: 'object#show', via: [:get], :as => :object
  resources :media_objects, except: [:create] do    
    member do
      put :update_status
      get :progress, :action => :show_progress
      get 'content/:datastream', :action => :deliver_content, :as => :inspect
      get 'track/:part', :action => :show, :as => :indexed_section
      get 'section/:content', :action => :show, :as => :pid_section
      get 'tree', :action => :tree, :as => :tree
      get :confirm_remove
      get 'archive',:action => :archive
      get 'manifest',:action => :manifest
    end
    collection do
      get :confirm_remove
      put :update_status
      delete :remove, :action => :destroy
      get :confirm_reassign_collection
      put :reassign_collection
    end
  end
  resources :master_files, except: [:new, :index, :update] do
    member do
      get  'thumbnail', :to => 'master_files#get_frame', :defaults => { :type => 'thumbnail' }
      get  'poster',    :to => 'master_files#get_frame', :defaults => { :type => 'poster' }

      post 'thumbnail', :to => 'master_files#set_frame', :defaults => { :type => 'thumbnail', :format => 'html' }
      post 'poster',    :to => 'master_files#set_frame', :defaults => { :type => 'poster', :format => 'html' }
      post 'still',     :to => 'master_files#set_frame', :defaults => { :format => 'html' }
      get :embed
      post 'attach_structure'
    end
  end

  match '/media_objects/:media_object_id/section/:id/embed' => 'master_files#embed', via: [:get]
  resources :derivatives, only: [:create]
  
  resources :comments, only: [:index, :create]

  namespace :admin do
    resources :groups, except: [:show] do 
      collection do 
        put 'update_multiple'
      end
      member do
        put 'update_users'
      end
    end
    resources :collections do
      member do
        get 'edit'
        get 'remove'
      end
    end
  end

  resources :dropbox, :only => [] do
    collection do
      delete :bulk_delete
    end
  end

  mount AboutPage::Engine => '/about(.:format)', :as => 'about_page'
  

end

app/models/admin/group.rb
# Copyright 2011-2015, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

require "role_controls"

module Admin
class Group
  extend ActiveModel::Naming
  include ActiveModel::Validations
  include ActiveModel::Conversion
  include ActiveModel::Dirty
  
  # For now this list is a hardcoded constant. Eventually it might be more flexible
  # as more thought is put into the process of providing a comment
  attr_accessor :name, :users
  validates :name, :presence => true
  validates :name, format: {
    without: /[\.;%\/]/,
    message: "must not contain any of the following: . ; % /" }

  def self.non_system_groups
    groups = all
    if system_groups = Avalon::Configuration.lookup('groups.system_groups')
      groups.reject! { |g| system_groups.include? g.name }
    end
    groups
  end
 
  def self.all
    groups = [] 
    RoleControls.roles.each do |role|
      groups << Admin::Group.find(role)
    end
    groups
  end

  def self.find(name)
    if RoleControls.roles.include? name
      # Creates a new object that looks like an old object
      group = self.new
      group.ignoring_changes do
        group.name = name
        group.users = RoleControls.users(name)
        group.new_record = false
        group.saved = true
      end
      group
    else
      nil
    end
  end

  def self.exists? name
    RoleControls.role_exists? name
  end

  def self.create(attributes = nil)
    group = Admin::Group.new
    if attributes.present?
      group.name = attributes[:name]
      if self.exists? group.name
      end
    end

    if group.valid?
      group.save
    else 
      return false
    end
 
    group
  end
  
  def self.new 
    g = super
    g.new_record = true
    g
  end

  def self.abstract_class?
    return false
  end

  def self.arel_table
    @arel_table ||= Arel::Table.new(nil, nil)
  end

  def new_record?
    @new_record
  end

  def new_record= val
    @new_record = val
  end
  
  def initialize(attributes = {})
    @saved = false
    @users = []
    attributes.each do |k, v|
      send("#{k}=", v)
    end
  end

  # These are needed so ActiveModel::Dirty works
  # and Group behaves like an ActiveRecord model
  def name
    @name
  end

  def name=(value)
    attribute_will_change!('name') if name != value and !@ignoring_changes
    @previous_name = name
    @name = value
  end

  def name_changed?
    changed.include?('name')
  end
  
  def users
    @users
  end

  def users=(value)
    attribute_will_change!('users') if users != value and !@ignoring_changes
    @users = value
  end

  def users_changed?
    changed.include?('users')
  end
  
  def resources
    res = []
  end
  
  def id 
    @name
  end
  
  # Necessary hack so that form_for works with both :new and :edit
  # FIXME This method is gnarly and doesn't allow everything that it should
  def save
    if new_record? && valid? && !self.class.exists?(name) 
      RoleControls.add_role(name)
      RoleControls.save_changes
      @saved = true
    elsif !new_record? && valid?
      if name_changed? && !@previous_name.eql?(name)
        RoleControls.remove_role @previous_name
        RoleControls.add_role name
        RoleControls.assign_users(users, name)
      end
      if users_changed?
        RoleControls.assign_users(users, name)
      end

      RoleControls.save_changes
      @saved = true
    elsif new_record? && valid? && self.class.exists?(name)
      errors.add(:name, "Group name already exists")
    else 
      @saved = false
    end 

    changed.clear if @saved 
    @saved
  end

  alias_method :save!, :save

  def delete 
    RoleControls.remove_role(name)
    RoleControls.save_changes
  end
  
  def ignoring_changes
    begin
      @ignoring_changes = true
      yield self
    ensure
      @ignoring_changes = false
    end
    return self
  end

  # Stub this method out so that form_for functions as expected for edit vs new
  # even though there is no database backing the Group model
  def persisted?
    @saved
  end
  
  def saved
    @saved
  end

  def saved= val 
    @saved = val
  end

  # Check to see if the name is static based on its inclusion in the system
  # group. This is a workaround for the bug that breaks the system whenever
  # a system group is renamed.
  def self.name_is_static? group_name
    Avalon::Configuration.lookup('groups.system_groups').include? group_name
  end
end
end

app/controllers/admin/groups_controller.rb
# Copyright 2011-2015, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed 
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the 
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

# -*- encoding : utf-8 -*-
require "role_controls"
class Admin::GroupsController < ApplicationController  
  before_filter :auth
  
  # Currently assumes that to do anything you have to be able to manage Group
  # TODO: finer controls
  def auth
    if current_user.nil? 
      flash[:notice] = "You need to login to manage groups"
      redirect_to new_user_session_path
    elsif cannot? :manage, Admin::Group
      flash[:notice] = "You do not have permission to manage groups"
      redirect_to root_path
    elsif params['id'].present?
      g = Admin::Group.find(params['id'])
      if cannot? :manage, g
        flash[:error] = "You must be an administrator to manage the '#{g.name}' group"
        redirect_to admin_groups_path
      end
    end
  end
  
  def index
    default_groups = Avalon::Configuration.lookup('groups.system_groups')
    @default_groups = []
    @groups = []

    #TODO: move RoleControls to Group model
    Admin::Group.all.each do |group|
      if default_groups.include? group.name 
        @default_groups << group
      else 
        @groups << group
      end
    end
  end
  
  def new
    @group = Admin::Group.new
  end
  
  def create
    name = params['admin_group'].strip
    if Admin::Group.exists?(name)
      flash[:error] = "Group name #{name} is taken."
      redirect_to admin_groups_path
      return
    end

    @group = Admin::Group.new
    @group.name = name
    if @group.save
      redirect_to edit_admin_group_path(@group)
    else
      flash[ :error ] = @group.errors
      redirect_to admin_groups_path
    end 
  end
  
  def edit
    @group = Admin::Group.find(params[:id])
  end
  
  def update
    #TODO: move RoleControls to Group model
    
   new_user = params["new_user"]
   new_group_name = params["group_name"]
   
    @group = Admin::Group.find(params["id"])

    # Make sure that the group is not part of the list of special system
    # groups. If it is then do not allow the name to be changed and cause
    # other things to break in the system
    #
    # It is not pretty but this gets the job done. Even though the view
    # prevents the name being changed this is a safeguard against somebody
    # posting it anyways
    if params["group_name"].present? and !@group.name.eql?(params["group_name"])
      if Admin::Group.name_is_static?(@group.name)
        flash[:error] = "Cannot change the name of a system group [#{new_group_name}]"
        redirect_to edit_admin_group_path(@group)
        return
      else
        # This logic makes sure that role is never blank even if the form
        # does not provide a value
        if Admin::Group.exists?(params["group_name"])
          flash[:error] = "Group name #{params["group_name"]} is taken."
          redirect_to edit_admin_group_path(@group)
          return
        end
        @group.name = new_group_name.blank? ? params["id"] : params["group_name"]
      end
    end
    @group.users += [new_user.strip] unless new_user.blank?
    
    if @group.save
      flash[:notice] = "Successfully updated group \"#{@group.name}\""
    end
    redirect_to edit_admin_group_path(@group) 
  end

  def destroy 
    Admin::Group.find(params[:id]).delete
    redirect_to admin_groups_path 
  end

  def update_users 
    group_name = params[:id]
    sole_managers = check_for_sole_managers if group_name == "manager"
    if !sole_managers.blank?
      flash[:error] = "Cannot remove users #{sole_managers.join(",")} because they are sole managers of collections."
    else
      users = RoleControls.users(group_name) - params[:user_ids] 
      RoleControls.assign_users(users, group_name)
      RoleControls.save_changes
    end
    redirect_to :back
  end

  # Only deletes multiple groups for now
  # TODO: able to add/remove an ability to multple groups
  def update_multiple
    params[:group_ids].each do |group_name|
      Admin::Group.find(group_name).delete
    end
    
    flash[:notice] = "Successfully deleted groups: #{params[:group_ids].join(", ")}"
    redirect_to admin_groups_path
  end

  def check_for_sole_managers
    sole_managers = []
    params["user_ids"].each do |manager|
      sole_managers << manager if Admin::Collection.all.any? {|c| c.managers == [manager]}
    end
    sole_managers
  end
end 

app/views/admin/groups/_form.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>

<% content_for :page_scripts do %>
  <%= javascript_include_tag 'autocomplete' %>
<% end %>

<div class="col-md-9 col-lg-8">
  <div class="container-fluid">
  <%= bootstrap_form_for @group  do |f| %>
    <h3>Group</h3>
    <% if @group.class.name_is_static? @group.name %>
      <p><%= @group.name %></p>
    <% else %>
      <div class="col-xs-6 col-sm-8">
        <%= text_field_tag :group_name, "Group name", value: @group.name, class: 'form-control' %>
      </div>
      <div class="col-xs-3 col-sm-2">
	<%= button_tag "Save", type: "submit", class: "btn btn-default col-xs-12" %>
      </div>
      <div class="col-xs-3 col-sm-2">
      <%= link_to "Delete Group", admin_group_path(@group.name), 
          method: :delete, confirm: "Deleted group cannot be recovered. Are you sure?", 
          class: "btn btn-danger col-xs-12" %>
      </div>
    <% end %>
  <% end %>
  </div>
  <div class="container-fluid">
    <%= bootstrap_form_for @group  do |f| %>
    <h3>Group Members</h3>
    <div class="col-xs-9 col-sm-10">
      <%= text_field_tag :new_user, nil, class: 'typeahead from-model form-control', 
          data: { model: 'user' }, placeholder: 'Enter a username' %>
    </div>
    <div class="col-xs-3 col-sm-2">
      <%= button_tag "Add user", type: "submit", class: "btn btn-default col-xs-12" %>
    </div>
  <% end %>
  </div>
  <div class="container-fluid">
  <%= form_tag update_users_admin_group_path, method: :put do %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-md-1"><input type="checkbox" class="select-groups"></th>
          <th class="col-md-10">Username</th>
          <th class="col-md-1"></th>
        </tr>
      </thead>
      <tbody>
        <% @group.users.each do |user| %>
          <tr>
            <td><%= check_box_tag "user_ids[]", user %></td>
            <td><%= user %></td>
            <td></td>
          </tr>
         <% end %>
       </tbody>
    </table>
  </div>
  <div class="container-fluid">
    <%= hidden_field_tag 'id', @group.name %>
    <%= submit_tag "Remove members", :method => :delete, class: "btn btn-danger delete", disabled: true  %>    
  </div>
  <% end %>
  </div>
</div>
<% content_for :page_scripts do %>
  <script>
    $('.select-groups').change(function(){
      $('input[id^=user_ids_]').prop('checked', $(this).is(':checked')).trigger('change');
    })
  
    $('input[id^=user_ids_]').change(function(){
      if ($(this).is(':checked')) {
        enableButtons();
      } else if ($(':checked').length == 0) {
        disableButtons();
      }
    })
  
    function enableButtons() {
      $('.delete').removeAttr('disabled');
    }

    function disableButtons() {
      $('.delete').attr('disabled', 'disabled');
    }
  </script>
<% end %>

app/views/admin/groups/edit.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% @page_title = t('groups.show.title', :group_name => @group.name, :application_name => application_name) %>

<div class="container-fluid">
  <%= render "form"%>
</div>

app/views/admin/groups/index.html.erb
<%#
Copyright 2011-2015, The Trustees of Indiana University and Northwestern
  University.  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed 
  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
  specific language governing permissions and limitations under the License.
---  END LICENSE_HEADER BLOCK  ---
%>
<% @page_title = t('groups.title', :application_name => application_name) %>

<div class="row col-md-9 col-lg-8">
  <div class="container-fluid">
    <h3>System Groups</h3>
      <table class="table table-striped ">
        <thead>
          <tr>
            <th>Group Name</th>
            <th>Members#</th>
          </tr>
        </thead>
        <tbody>
          <% @default_groups.each do |group|%>
            <tr>
              <td><%= link_to_if can?(:manage, group), group.name, edit_admin_group_path(group) %></td>
              <td><%= group.users.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
  <div class="container-fluid">
    <h3> Additional Groups</h3>

    <%= form_tag(admin_groups_path) do -%>
      <div class="col-xs-9 col-sm-10">
        <%= text_field_tag 'admin_group', nil, :placeholder => 'Enter group name here...', class: 'form-control' %> 
      </div>
      <%= button_tag 'Create Group', type: 'submit', class: 'btn btn-default col-xs-3 col-sm-2' %>
    <% end -%>

  </div>
  <div class="container-fluid">
    <%= form_tag update_multiple_admin_groups_path, method: :put do %>

      <table class="table table-striped">
        <thead>
          <tr>
            <th><input type="checkbox" class="select-groups"></th>
            <th>Group Name</th>
            <th>Members#</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group|%>
            <tr>
              <td><%= check_box_tag "group_ids[]", group.name %></td>
              <td><%= link_to group.name, edit_admin_group_path(group) %></td>
              <td><%= group.users.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= submit_tag "Delete Groups", method: :delete, 
        confirm: "Deleted groups cannot be recovered. Are you sure?", 
        class: "btn btn-danger delete", disabled: true %>
    <% end %>
  </div>
</div>

<% content_for :page_scripts do %>
  <script>
    $('.close').click(function(){
      $(this).parent().remove();
    })
  
    $('.select-groups').change(function(){
      $('input[id^=group_ids_]').prop('checked', $(this).is(':checked')).trigger('change');
    })
  
    $('input[id^=group_ids_]').change(function(){
      if ($(this).is(':checked')) {
        enableButtons();
      } else if ($(':checked').length == 0) {
        disableButtons();
      }
    })
  
    function enableButtons() {
      $('#add-ability').removeClass('disabled');
      $('#remove-ability').removeClass('disabled');    
      $('.delete').removeAttr('disabled');
    }

    function disableButtons() {
      $('#add-ability').addClass('disabled');
      $('#remove-ability').addClass('disabled');    
      $('.delete').attr('disabled', 'disabled');
    }
  </script>
<% end %>